// 1º PASSO: IMPORTAR O POOL NO ARQUIVO CONEXÃO.JS
const pool = require('../conexao-banco-de-dados/conexao')

//2º PASSO: CRIAR A FUNÇÃO QUE SERÁ EXECUTADA NA ROTA E APÓS,  IMPLEMENTAR NO CÓDIGO DE EXECUÇÃO EM ROTAS O NOME DA FUNÇÃO NO 6º PASSO DO ARQUIVO DE ROTAS.JS


// 3º PASSO: EXPORTAR A FUNÇÃO/CONTROLADOR
module.exports = {

}
